AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - examples/**/*
require:
  - rubocop-performance

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  CountComments: false
  Max: 25

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: true
