require "cgi"
require "json"
require 'rest-client'
require "uri"
require_relative 'bigcommerce/api'
require_relative 'bigcommerce/connection'
require_relative 'bigcommerce/version'
require_relative 'bigcommerce/resource'
require_relative 'bigcommerce/product'
