require "cgi"
require "json"
require 'rest-client'
require 'oauth2'
require "uri"
require 'bigcommerce/api'
require 'bigcommerce/connection'
require 'bigcommerce/version'
require 'bigcommerce/resource'
require 'bigcommerce/product'
